public class Player {
    private int stack;
    private Hand hand;
    private int position;

    // A player can be generated by specifying their
    public Player( int stack, int position ) {
        this.stack = stack;
        this.position = position;
    }

    public void dealHand( Hand hand ) {
        this.hand = hand;
    }
}
